#! /bin/bash

#
# gemini
# ====
#
# NAME
# ----
# gemini -- tiny bundler wrapper
#
# USAGE
# ----
# ```
#  * gemini                 # Considerate `bundle install` (Accept env `gemini_path` and `gemini_binstubs`)
#  * gemini [-h|--help]     # Show this help.
#  * gemini [-j|--dry-run]  # Show bundle install plot (No installation is performed)
#  * gemini [-v|--verbose]  # Considerate bundle install with verbose.
#  * gemini version         # Show gemini version info.
#  * gemini purge           # Clean up `.bundle`, boilerplatings and bundled-files
#  * gemini clean           # Clean up boilerplatings and bundled files
#  * gemini set-config      # Set bundle config (Accept env `gemini_path` and `gemini_binstubs`)
#  * gemini show-config     # Show bundle config
#  * gemini install-bundler # exec `gem install bundler`
# ```
#
# Author
#
# Copyright (c) 2020 Hiroshi IKEGAMI
#
# MIT License
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
#
#

set -eu

current=""

export GEMINI_DEFAULT_PATH_SUFFIX="${GEMINI_DEFAULT_PATH_SUFFIX:-".bundle"}"
export GEMINI_DEFAULT_PATH_VENDOR_SUFFIX="${GEMINI_DEFAULT_PATH_VENDOR_SUFFIX:-"vendor/bundle"}"
export GEMINI_DEFAULT_BINSTUBS_SUFFIX=${GEMINI_DEFAULT_BINSTUBS_SUFFIX:-".bundle/bin"}
export GEMINI_DEFAULT_BINSTUBS_VENDOR_SUFFIX=${GEMINI_DEFAULT_BINSTUBS_VENDOR_SUFFIX:-"vendor/bin"}

gemini::usage::exit() {
    cat << HELP
USAGE:
    * gemini                 # Considerate \`bundle install\` (Accept env \`gemini_path\` and \`gemini_binstubs\`)
    * gemini [-h|--help]     # Show this help.
    * gemini [-j|--dry-run]  # Show bundle install plot (No installation is performed)
    * gemini [-v|--verbose]  # Considerate bundle install with verbose.
    * gemini version         # Show gemini version info.
    * gemini purge           # Clean up \`.bundle\`,  boilerplatings and  bundled-files
    * gemini clean           # Clean up boilerplatings and bundled files
    * gemini set-config      # Set bundle config (Accept env \`gemini_path\` and \`gemini_binstubs\`)
    * gemini show-config     # Show bundle config
    * gemini install-bundler # exec \`gem install bundler\`
HELP
    exit 1
}

gemini::version::show() {
    echo "gemini version 1.0.0"
}

gemini::bundle::install() {
    gemini::cd::gemfile::path
    bundle install
}

gemini::path::fix() {
    bundle_path="${gemini_path:-"${current}/${GEMINI_DEFAULT_PATH_SUFFIX}"}"
    binstubs_path="${gemini_binstubs:-"${current}/${GEMINI_DEFAULT_BINSTUBS_SUFFIX}"}"

    if [ -e "${current}/vendor" ];then
        bundle_path="${gemini_path:-"${current}/${GEMINI_DEFAULT_PATH_VENDOR_SUFFIX}"}"
        binstubs_path="${gemini_binstubs:-"${current}/${GEMINI_DEFAULT_BINSTUBS_VENDOR_SUFFIX}"}"
    fi
    export bundle_path
    export binstubs_path
}

gemini::config::set() {
    gemini::cd::gemfile::path
    gemini::path::fix

    echo "bundle config --local path "${bundle_path}""
    bundle config --local path "${bundle_path}"
    echo "bundle config --local bin  "${binstubs_path}""
    bundle config --local bin  "${binstubs_path}"
}

gemini::cd::gemfile::path() {
    pwddir="$(pwd)"
    while true;do
        [ -e "${pwddir}/Gemfile" ] && break
        if [ "$(cd "$pwddir"; pwd -P)" = "/" ];then
            echo "Error: Gemfile not found."
            exit 1
        fi
        pwddir="${pwddir}/../"
    done

    current="$(cd "$pwddir"; pwd -P)"

    cd "${current}"
}

gemini::bundle::install::plot() {
    gemini::cd::gemfile::path
    gemini::path::fix

    echo "detected Gemfile --"
    echo "${current}/Gemfile"
    echo
    echo "--------------"

    echo
    echo "bundled gems --"
    bundle list
    echo
    echo "--------------"

    echo
    echo "bundle config --"
    echo

    echo "-- bundle config --local path "${bundle_path}""
    echo
    echo "-- bundle config --local bin  "${binstubs_path}""

}

gemini::config::show() {
    gemini::cd::gemfile::path
    bundle config
}

gemini::bundler() {
    exec gem install bundler
}

gemini::bundle::clean() {
    gemini::cd::gemfile::path

    if [ -e "${current}/.bundle" ];then
        echo "rm -fr "${current}/.bundle""
        rm -fr "${current}/.bundle"
    fi
}

gemini::clean() {
    gemini::cd::gemfile::path
    gemini::path::fix

    for x in $(echo "${bundle_path}" "${binstubs_path}");do
        if [ -e "${x}" ];then
            echo "rm -fr "${x}""
            rm -fr "${x}"
        fi
    done
}

if [ "$#" = 0 ];then
    gemini::config::set
    gemini::bundle::install
    exit 0;
fi

case "${1}" in
    version)
        gemini::version::show
        exit 0
        ;;
    set-config)
        gemini::config::set
        gemini::config::show
        exit 0
        ;;
    show-config)
        gemini::config::show
        exit 0
        ;;
    purge)
        gemini::bundle::clean
        gemini::clean
        exit 0
        ;;
    clean)
        gemini::clean
        exit 0
        ;;
    install-bundler)
        gemini::bundler
        exit 0
        ;;
    *)
        if [[ ! "${1}" =~ ^- ]];then
            echo "Unknown option ${@}" >&2
            exit 1
        fi
        ;;
esac

optspec=":-:hvj"
while getopts "$optspec" optchar; do
    case "${optchar}" in
        -)
            case "${OPTARG}" in
                dry-run)
                    gemini::bundle::install::plot
                    exit 0
                    ;;
                verbose)
                    gemini::config::set
                    gemini::config::show
                    gemini::bundle::install
                    exit 0
                    ;;
                help)
                    gemini::usage::exit && exit 1
                    ;;
                *)
                    echo "Unknown option ${@}" >&2
                    exit 1
                    ;;
            esac
            ;;
        j)
            gemini::bundle::install::plot
            exit 0
            ;;
        v)
            gemini::config::set
            gemini::config::show
            gemini::bundle::install
            exit 0
            ;;
        h)
            gemini::usage::exit; exit 1
            ;;
        *)
            echo "Unknown option ${@}" >&2
            exit 1
            ;;

    esac
done


