.nh
.TH "gemini" "1"
.SH NAME
.PP
gemini \-\- tiny bundler wrapper

.SH USAGE
.PP
.RS

.nf
 * gemini [bundle\-install] # Considerate `bundle install` (Accept env `gemini_path` and `gemini_binstubs`)
 * gemini [\-h|\-\-help]      # Show this help.
 * gemini [\-j|\-\-dry\-run]   # Show bundle install plot (No installation is performed)
 * gemini [\-v|\-\-verbose]   # Considerate bundle install with verbose.
 * gemini [\-\-force]        # force config (path and bin), and exec `gemini bundle\-install`.
 * gemini init             # initialize config (path and bin), and exec \`gemini bundle-install\`.
 * gemini version          # Show gemini version info.
 * gemini purge            # Clean up `.bundle`, boilerplatings and bundled-files
 * gemini clean            # Clean up boilerplatings and bundled files
 * gemini set-config       # Set bundle config (Accept env `gemini_path` and `gemini_binstubs`)
 * gemini show-config      # Show bundle config
 * gemini install-bundler  # exec `gem install bundler`

.fi
.RE

.PP
Author

.PP
Copyright (c) 2020 Hiroshi IKEGAMI

.PP
MIT License

.PP
Permission is hereby granted, free of charge, to any person obtaining
.br
a copy of this software and associated documentation files (the
.br
"Software"), to deal in the Software without restriction, including
.br
without limitation the rights to use, copy, modify, merge, publish,
.br
distribute, sublicense, and/or sell copies of the Software, and to
.br
permit persons to whom the Software is furnished to do so, subject to
.br
the following conditions:
.br

.PP
The above copyright notice and this permission notice shall be
.br
included in all copies or substantial portions of the Software.
.br

.PP
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
.br
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
.br
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
.br
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
.br
LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
.br
OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
.br
WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
.br
